server:
  host: "0.0.0.0"
  port: 8000
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"

services:
  auth:
    name: "auth-service"
    url: "http://auth-service:8001"
    timeout: "30s"
    health_path: "/health"
    enabled: true

  profile:
    name: "profile-service"
    url: "http://user-profile-service:8002"
    timeout: "30s"
    health_path: "/health"
    enabled: true

  products:
    name: "product-service"
    url: "http://product-service:8004"
    timeout: "30s"
    health_path: "/health"
    enabled: true

  cart:
    name: "cart-service"
    url: "http://cart-service:8007"
    timeout: "30s"
    health_path: "/health"
    enabled: true

  orders:
    name: "order-service"
    url: "http://order-service:8008"
    timeout: "30s"
    health_path: "/health"
    enabled: true

  payments:
    name: "payment-service"
    url: "http://payment-service:8009"
    timeout: "30s"
    health_path: "/health"
    enabled: true

  notifications:
    name: "notification-service"
    url: "http://notification-service:8011"
    timeout: "30s"
    health_path: "/health"
    enabled: true

routes:
  - path: "/api/auth/*"
    service_name: "auth"
    strip_prefix: false
    auth_required: false

  - path: "/api/profile/*"
    service_name: "profile"
    strip_prefix: false
    auth_required: true

  - path: "/api/products/*"
    service_name: "products"
    strip_prefix: false
    auth_required: false

  - path: "/api/cart/*"
    service_name: "cart"
    strip_prefix: false
    auth_required: true

  - path: "/api/orders/*"
    service_name: "orders"
    strip_prefix: false
    auth_required: true

  - path: "/api/payments/*"
    service_name: "payments"
    strip_prefix: false
    auth_required: true

  - path: "/api/notifications/*"
    service_name: "notifications"
    strip_prefix: false
    auth_required: true

rate_limit:
  name: "default"
  requests: 100
  window: "1m"
  burst: 200
  scope: "per_ip"
  enabled: true

circuit_breaker:
  max_requests: 3
  interval: "60s"
  timeout: "30s"
  failure_threshold: 0.6

auth:
  service_url: "http://auth-service:8001"
  timeout: "5s"
  cache_ttl: "5m"
  skip_paths:
    - "/health"
    - "/health/ready"
    - "/gateway/services"
    - "/gateway/routes"
    - "/gateway/metrics"
    - "/api/auth/login"
    - "/api/auth/register"

logging:
  level: "info"
  format: "json"