version: '3.8'

services:
  order-service:
    build: .
    container_name: order-service
    ports:
      - "8008:8008"
    environment:
      - DATABASE_URL=postgresql://orderuser:orderpass@order-postgres:5432/orderdb
      - AUTH_SERVICE_URL=http://auth-service:8001
      - CART_SERVICE_URL=http://cart-service:8007
      - PRODUCT_SERVICE_URL=http://product-service:8004
      - ENVIRONMENT=docker
      - LOG_LEVEL=INFO
    depends_on:
      - order-postgres
    networks:
      - project-zero-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8008/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  order-postgres:
    image: postgres:15-alpine
    container_name: order-postgres
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: orderuser
      POSTGRES_PASSWORD: orderpass
    volumes:
      - order_postgres_data:/var/lib/postgresql/data
    networks:
      - project-zero-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orderuser -d orderdb"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  order_postgres_data:

networks:
  project-zero-net:
    external: true