run:
  timeout: 5m
  go: "1.20"

linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - ineffassign
    - misspell
    - gocyclo
    - unparam
    - unused
    - gosec
    - staticcheck

linters-settings:
  gocyclo:
    min-complexity: 15
  golint:
    min-confidence: 0.8
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - golint